// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/*";
  };
  "./pages/LoginPage.tsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "catchall.tsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/LoginPage": typeof import("./src/./pages/LoginPage.tsx");
  "catchall": typeof import("./src/catchall.tsx");
};